services:

  neo4j:
    image: neo4j
    ports:
      - 7687:7687
    environment:
      # disable authentication as it's not the object of test assessment
      NEO4J_AUTH: none

  web:
    build:
      context: .
    ports:
      - 80:80
    working_dir: "/app"
    command: "uvicorn app:app --host 0.0.0.0 --port 80"
